version: "3"

services:
  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - database
    environment:
      database__client: mysql
      database__connection__host: database
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
    networks:
      - my-network

  database:
    image: mysql:5.7
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - my-network

volumes:
  database-data:

networks:
  my-network: